"""Add match event relationship

Revision ID: 2284eee3c569
Revises: 040ee0556b33
Create Date: 2026-08-27 19:30:01.791800

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2284eee3c569'
down_revision: Union[str, Sequence[str], None] = '040ee0556b33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('match_logs', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('event_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key("event_matchlog", 'events', [
                                    'event_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('match_logs', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('event_id')

    # ### end Alembic commands ###
