"""Add match team relationship

Revision ID: 5b71fae1ce93
Revises: 2284eee3c569
Create Date: 2026-08-27 19:33:21.790587

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b71fae1ce93'
down_revision: Union[str, Sequence[str], None] = '2284eee3c569'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('match_logs', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('team_a_id', sa.Integer(), nullable=False))
        batch_op.add_column(
            sa.Column('team_b_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key("match_teamb", 'teams', ['team_b_id'], [
                                    'id'], ondelete='CASCADE')
        batch_op.create_foreign_key("match_teama", 'teams', ['team_a_id'], [
                                    'id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('match_logs', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('team_b_id')
        batch_op.drop_column('team_a_id')

    # ### end Alembic commands ###
