"""Add club player relationship

Revision ID: 5f07f4b211ef
Revises: adf0e6ca93aa
Create Date: 2026-08-27 19:11:00.502813

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f07f4b211ef'
down_revision: Union[str, Sequence[str], None] = 'adf0e6ca93aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('club_player',
    sa.Column('club_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('club_id', 'player_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('club_player')
    # ### end Alembic commands ###
