"""added new fields to event

Revision ID: 68418ec03445
Revises: d370c1761536
Create Date: 2026-09-23 23:31:38.391725

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68418ec03445'
down_revision: Union[str, Sequence[str], None] = 'd370c1761536'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(length=200), nullable=False))
        batch_op.add_column(sa.Column('max_players', sa.Integer(), nullable=False))
        batch_op.drop_column('type')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.VARCHAR(length=200), nullable=False))
        batch_op.drop_column('max_players')
        batch_op.drop_column('description')

    # ### end Alembic commands ###
