"""Add event and club relation

Revision ID: 6a1ca52f7fbc
Revises: ae1db1289a4e
Create Date: 2026-09-07 21:54:44.622417

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a1ca52f7fbc'
down_revision: Union[str, Sequence[str], None] = 'ae1db1289a4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('club_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key("club_event_relation", 'clubs', [
                                    'club_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('club_id')

    # ### end Alembic commands ###
