"""Add club player as admin relationship

Revision ID: adf0e6ca93aa
Revises: c15045c0ad4a
Create Date: 2026-08-27 19:03:49.871408

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'adf0e6ca93aa'
down_revision: Union[str, Sequence[str], None] = 'c15045c0ad4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('club_admin',
    sa.Column('club_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('club_id', 'player_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('club_admin')
    # ### end Alembic commands ###
